services:
  - type: web
    name: financial-guide-bot  # Имя твоего сервиса
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: BOT_TOKEN
        sync: false  # Введи вручную в дашборде
      - key: WEBHOOK_URL
        generateValue: true  # Render сам сгенерирует после деплоя
    autoDeploy: true
